name: Rust CI Tests

on:
  pull_request:
    types: [opened, synchronize, reopened, ready_for_review]
    branches: [ $default-branch, 'feat/**', release-candidate ]
  merge_group:

concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref || github.run_id }}
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest
    # Uncomment for a more powerful runner, can also use 16 or 32 vCPUs
    #runs-on: buildjet-8vcpu-ubuntu-2204
    steps:
      # Set Rust env vars
      - uses: actions/checkout@v4
        with:
          repository: lurk-lab/ci-workflows
      - uses: ./.github/actions/ci-env
      - uses: actions/checkout@v4
        # Uncomment for lurk-rs or other repos with submodule
        #with:
        #  submodules: recursive
      - uses: dtolnay/rust-toolchain@stable
      - uses: taiki-e/install-action@nextest
      - uses: Swatinem/rust-cache@v2
      # Testing steps go here
      #- name: Rust tests
      #  run: |
      #    cargo nextest run --profile ci --workspace --cargo-profile dev-ci
